name: 'Terraform'

on:
#  push:
#    branches: [ "main" ]
#  pull_request:

#permissions:
#  contents: read
  
 workflow_dispatch:
 
permissions:
 id-token: write
 contents: read
 actions: read
 security-events: write
 pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.OPA_Result.outputs.test }}
    environment: production

    steps:
    #- uses: terraform-compliance/github_action@main
    
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -no-color

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
    #  run: terraform fmt -check
    
        
    # - name: Add Firewall rule
    #   id: add_firewallrule
    #   shell: bash
    #   run: |
    #         agentIP=$(curl -s https://api.ipify.org/)
    #         az keyvault network-rule add --resource-group test-rg --name test-kv1441 --ip-address $agentIP
    #         sleep 50s
    #         echo $agentIP
    #         terraform plan -input=false -var-file=terra.tfvars -no-color -target='null_resource.kv-keys-add' -out='ip.tfplan'
    #         terraform apply ip.tfplan


    # #Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -var-file=terra.tfvars -no-color -out=tfplan.plan && terraform show -json tfplan.plan | grep '^{.*}$' > tfplan.json
      
    #- name: Print JSON
    #  run: |
    #    JSON=$(cat ./tfplan.json)
    #    echo "${JSON//'%'/'%25'}"
      
    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest
        
    #- name: Directory 1 commands
    #  run: | 
    #   ls -l tfplan.json 
    
    #- name: Directory 2 commands
    #  run: chmod 777 tfplan.json
      
    #- name: Directory 3 commands
    #  run: ls -l tfplan.json
      
    #- name: Print JSON 3
    #  run: |
    #    JSON=$(cat tfplan.json)
    #    echo "${JSON//'%'/'%25'}"      
       
    - name: Run OPA Tests
      id: OPA_Result
      #run: opa version
      #run: opa eval --decision test  --bundle ${{ github.workspace }}/tests3 tfplan.json 
      #run: opa exec --decision production/warn  --bundle ${{ github.workspace }}/tests/ ${{ github.workspace }}/tests/tfplan.json  
      #run: opa eval --data ${{ github.workspace }}/tests1/ -i tfplan.json data.terraform.tag_validation/deny
      run: opa exec --decision production/deny --bundle ${{ github.workspace }}/tests/ "tfplan.json" --format json > result.json
      #run: opa bench --bundle ${{ github.workspace }}/tests/ -i tfplan.json 'production/deny'
      
     
    - name: OPA Policy Result Check
      id: opa_result_parse
      run: |
       tesst=$(jq '.result[0].result' result.json)
       if [[ ${{tesst}} == [] ]]; then
           continue;
       else
           exit 1
       fi
       echo "${tesst}"
       #echo "${JSON//'%'/'%25'}"
       #echo "::set-output name=opa_result::$JSON"
       #exit 1
       
    #- name: OPA tests
    #  uses: ibiqlik/conftest-action-docker@master
    #  with:
    #    path: "tfplan.json"
      
    #- name: terraform-compliance
    #  id: terraform-compliance-from-local
    #  run: |
    #      terraform-compliance --decision production/warn plan.out.json --bundle ${{ github.workspace }}/tests/ 

    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v3.1.2
    #  with:
    #    name: ip-plan
    #    path: ip.plan

    #- name: Download
    #  uses: actions/download-artifact@v3
    #  with: 
    #    name: ip.plan
    # - name: Remove Firewall rule
    #   id: remove_firewallrule
    #   shell: bash
    #   run: |
    #         agentIP=$(curl -s https://api.ipify.org/)
    #         az keyvault network-rule remove --resource-group test-rg --name test-kv1441 --ip-address $agentIP
    #         sleep 50s
    #         echo $agentIP
      
      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
    #  if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve ip.plan

    - name: Terraform Plan - 1
      run: terraform plan -input=false -var-file=terra.tfvars -no-color 

    - name: Terraform Apply - 1
    #  if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -var-file=terra.tfvars
